import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./ReactQueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Theme>  */}

      <QueryClientProvider> 
        <AuthProvider >  
          <Theme accentColor="bronze" grayColor="gray" panelBackground="solid" radius="full" scaling="110%">
        <NavBar />
        <main className="p-5">
          <Container > 
          {children}
          </Container>
      
        </main>
        {/* <ThemePanel/> */}
        </Theme>
        </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
